---
- name: redhat | add repository
  template:
    src: "{{ nginx_repo_template }}.{{ nginx_repo_version }}.j2"
    dest: /etc/yum.repos.d/nginx.repo
  tags:
    - nginx-repo
    - nginx-repo:repository
