---
- name: "debian | set key name"
  set_fact:
    nginx_repo_key_name: "{{nginx_repo_key|basename}}"
  tags:
    - nginx-repo
    - nginx-repo:key

- name: "debian | download key"
  local_action:
    get_url url="{{nginx_repo_key}}" dest="{{ nginx_repo_cache_dir }}/{{ nginx_repo_key_name }}"
  become: no
  run_once: true
  tags:
    - nginx-repo
    - nginx-repo:key

- name: debian | import key
  apt_key:
    data: "{{ file_item }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/nginx.gpg
  with_file:
    - "{{ nginx_repo_cache_dir }}/{{ nginx_repo_key_name }}"
  loop_control:
    loop_var: file_item
  tags:
    - nginx-repo
    - nginx-repo:key
