---
- name: "key name (common)"
  set_fact:
    nginx_repo_key_file: "{{ nginx_repo_key | basename}}"

- name: "download key (common)"
  local_action:
    get_url url="{{nginx_repo_key}}" dest="{{ nginx_repo_cache_dir }}/{{ nginx_repo_key_file }}"
  become: no
  run_once: true

- name: "copy key (common)"
  copy:
    src: "{{ nginx_repo_cache_dir }}/{{ nginx_repo_key_file }}"
    dest: "{{ nginx_repo_tmp_dir }}/{{ nginx_repo_key_file }}"
    owner: root
    group: root
    mode: 0644
