---

- name: "os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
    - "os-default.yml"
  tags:
    - always

- name: include packages tasks
  ansible.builtin.include_tasks:
    file: repository-{{ ansible_os_family }}.yml
    apply:
      tags:
        - nginx_repo
  when: nginx_repo_supported
