---
- name: "add repository (debian)"
  template:
    src: "{{ nginx_repo_template }}.{{ nginx_repo_version }}.j2"
    dest: /etc/apt/sources.list.d/nginx.list
  register: repository

- name: "repository update (debian)"
  apt:
    cache_valid_time: 0
    update_cache: yes
  when: repository|changed
