---

- name: "Add nginx repository"
  ansible.builtin.template:
    src: "repository-Redhat.j2"
    dest: "{{ nginx_repo_file }}"
    owner: root
    group: root
    mode: "0644"
  when: nginx_repo_state

- name: "Remove nginx repository"
  ansible.builtin.file:
    path: "{{ nginx_repo_file }}"
    state: absent
  when: not nginx_repo_state
